version: "3"
networks:
  expense: # docker network create expense
volumes:
  mysql: # docker volumes create mysql
services:
  mysql:
    image: muneer092/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
  backend:
    image: muneer092/backend:v1
    container_name: backend 
    command: sh -c "sleeps 10 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: muneer092/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend

    




